#!/usr/bin/env node
/* Extracts the MonoLock DSP engine from prototypes/monolock-prototype.html into
   src/monolock-engine.generated.js so it can be require()'d by tests and read
   as plain source.

   The HTML remains the SINGLE SOURCE OF TRUTH. Everything above the
   "app state" marker in the prototype's <script> is pure DSP with no DOM
   references; everything below is UI. Never hand-edit the generated file —
   edit the HTML and re-run `npm run extract`. */
const fs=require('fs'),path=require('path');

const ROOT=path.join(__dirname,'..');
const SRC=path.join(ROOT,'prototypes','monolock-prototype.html');
const OUT=path.join(ROOT,'src','monolock-engine.generated.js');
const MARK='/* ========================= app state ========================= */';

const html=fs.readFileSync(SRC,'utf-8');
const script=html.split('<script>')[1].split('</script>')[0];
if(script.indexOf(MARK)<0){
  console.error('FATAL: app-state marker not found. The prototype layout changed —\n'+
    'update MARK in tools/extract-engine.js to the new DSP/UI boundary.');
  process.exit(1);
}
const engine=script.split(MARK)[0];

// Collect top-level declarations (column 0) so the module exports everything the
// engine defines, without maintaining a hand-written list that silently rots.
const names=new Set();
for(const re of [/^(?:async\s+)?function\s+(\w+)/gm,/^class\s+(\w+)/gm,/^const\s+(\w+)\s*=/gm,/^let\s+(\w+)\s*=/gm]){
  for(const m of engine.matchAll(re))names.add(m[1]);
}
const list=[...names].sort();

const banner=
`/* AUTO-GENERATED by tools/extract-engine.js — DO NOT EDIT.
   Source of truth: prototypes/monolock-prototype.html
   Regenerate with: npm run extract
   Generated: ${new Date().toISOString().slice(0,10)}
   Exports: ${list.join(', ')} */\n\n`;

const footer=`\n/* --- module surface --- */\nif(typeof module!=='undefined'&&module.exports){\n  module.exports={${list.join(', ')}};\n}\n`;

fs.writeFileSync(OUT,banner+engine+footer);
console.log('wrote '+path.relative(ROOT,OUT)+' ('+(banner+engine+footer).length+' bytes, '+list.length+' exports)');
