#!/usr/bin/env node
/* Extracts the MonoLock DSP engine from prototypes/monolock-prototype.html into
   src/monolock-engine.generated.js so it can be require()'d by tests and read
   as plain source.

   The HTML remains the SINGLE SOURCE OF TRUTH. Everything above the
   "app state" marker in the prototype's <script> is pure DSP with no DOM
   references; everything below is UI. Never hand-edit the generated file —
   edit the HTML and re-run `npm run extract`. */
const fs=require('fs'),path=require('path');

const ROOT=path.join(__dirname,'..');
const SRC=path.join(ROOT,'prototypes','monolock-prototype.html');
const OUT=path.join(ROOT,'src','monolock-engine.generated.js');
const MARK='/* ========================= app state ========================= */';

const html=fs.readFileSync(SRC,'utf-8');
// Pick the <script> block that actually contains the DSP/UI marker, rather than
// assuming it is the first one and that the tag has no attributes. The old
// html.split('<script>')[1] broke on an added analytics tag or a `type="module"`
// attribute — loudly, but for a reason that took a while to see.
const blocks=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const script=blocks.find(b=>b.indexOf(MARK)>=0);
if(!script){
  console.error('FATAL: app-state marker not found in any of the '+blocks.length+
    ' <script> block(s). The prototype layout changed —\n'+
    'update MARK in tools/extract-engine.js to the new DSP/UI boundary.');
  process.exit(1);
}
const engine=script.split(MARK)[0];

// Collect top-level declarations (column 0) so the module exports everything the
// engine defines, without maintaining a hand-written list that silently rots.
const names=new Set();
for(const re of [/^(?:async\s+)?function\s+(\w+)/gm,/^class\s+(\w+)/gm,/^const\s+(\w+)\s*=/gm,/^let\s+(\w+)\s*=/gm]){
  for(const m of engine.matchAll(re))names.add(m[1]);
}
const list=[...names].sort();

// No timestamp in the banner: the generated file is committed, and `npm test`
// regenerates it, so embedding new Date() made the file's content change every
// day and dirtied the working tree on every test run. The output is now a pure
// function of the prototype.
const banner=
`/* AUTO-GENERATED by tools/extract-engine.js — DO NOT EDIT.
   Source of truth: prototypes/monolock-prototype.html
   Regenerate with: npm run extract
   Exports: ${list.join(', ')} */\n\n`;

const footer=`\n/* --- module surface --- */\nif(typeof module!=='undefined'&&module.exports){\n  module.exports={${list.join(', ')}};\n}\n`;

fs.writeFileSync(OUT,banner+engine+footer);
console.log('wrote '+path.relative(ROOT,OUT)+' ('+(banner+engine+footer).length+' bytes, '+list.length+' exports)');
